name: Tests

on:
  push:
    paths:
      - 'src/mdchat/**'
      - 'tests/**'
    branches:
      - main
  pull_request:
    paths:
      - 'src/mdchat/**'
      - 'tests/**'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      - name: Setup a local environment for Poetry
        run: | 
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
      
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        run: poetry install

      - name: Run Pytests
        run: poetry run pytest -v
